
# @TODO: use docker registry here and then build with it

image: gcc:latest

variables:
  BUILD_PATH: ./build/
  BUILD_TYPE: Release
  CMAKE_OPTIONS: ""
  CC: gcc
  CXX: g++
  GCOV: gcov
  #COVERAGE: "1"


before_script:
  - apt-get -qq update && apt-get -qq install -y gcc g++ clang cmake make binutils
  - "chmod +x ./scripts/*.sh"
  - ./scripts/install-deps.sh

cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: true
  paths:
    - build/

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - ./scripts/prebuild.sh
    - ./scripts/build.sh

test:
  stage: test
  script:
    - ./scripts/prebuild.sh
    - ./scripts/build.sh
    - ./scripts/run-tests.sh